# Generated by Django 3.2.9 on 2021-11-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport_code',
            field=models.CharField(default='test', max_length=40, verbose_name='код пасспорта'),
            preserve_default=False,
        ),
    ]
