# Generated by Django 3.2.9 on 2021-11-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_passport_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_codes/', verbose_name='qr-код'),
        ),
    ]
