# Generated by Django 3.2.9 on 2021-11-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
