# Generated by Django 3.2.9 on 2021-11-19 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0002_auto_20211119_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена'),
            preserve_default=False,
        ),
    ]
