# Generated by Django 3.2.9 on 2021-11-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0003_storage_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseorder',
            name='comment',
        ),
        migrations.AddField(
            model_name='seasonorder',
            name='season_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='selfstorage.seasonservice', verbose_name='что на хранении'),
        ),
    ]
